### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by sumatevanaleesuksun** [usc-isi-i2/kgtk-similarity#7]
Hello Team!

Your project is perfect that's help me to understanding about KGTK model. However, I found error about 502 Bad Gateway when I use API "https://kgtk.isi.edu/similarity_api?q1=Q35064&q2=Q23835560&similarity_type=complex". Please fix it asap!

**Comment by saggu** [comment]
The service is back up

**Comment by sumatevanaleesuksun** [comment]
Thx! However, I found error about 502 Bad Gateway again. Do you have plan/timeline routine for backup?

**Comment by saggu** [comment]
Back up now, the service got killed due to heavy usage. Please limit the rate of queries.
